apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
 DB_HOST: mysql # mysql service name 
  

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels:
    component: backend
    project: expense
    module: backend

spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      module: backend
  template:
    metadata:
      labels:
        component: backend
        project: expense
        module: backend
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
      envFrom:
      - configMapRef:
          name: backend # The ConfigMap this value comes from.
              
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  selector:
      component: backend
      project: expense
      module: bakend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
