apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
  #DB_HOST: db-dev.daws78s.online
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    module: app
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      module: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        module: app
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
      envFrom:
      - name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  selector:
      component: backend
      project: expense
      module: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
