apiVersion: apps/v1
kind: Deployment
metadata: 
  name: expense
  namespace: expense
  labels:
    component: mysql
    project: expense
    module: db
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      module: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        module: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  selector:
      component: mysql
      project: expense
      module: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
