apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: expense
  labels:
    tier: hari-nginx

spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: hari-nginx
  template:
    metadata:
      labels:
        tier: hari-nginx
    spec:
      containers:
      - name: nginx
        image: nginx 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    tier: hari-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30007
  type: LoadBalancer
