apiVersion: apps/v1
kind: ReplicaSet

metadata: 
  name: nginx-replica
  labels:
    project: expense

spec:
  replicas: 2
  selector:
    matchLabels: 
      tier: hari-nginx
  template:
    metadata:
      labels:
        tier: hari-nginx
    spec:
      containers:
      - name: nginx
        image: nginx

