apiversion: v1
kind: Replicaset

metadata: 
  name: expense
  labels:
    tier: hari-nginx

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: hari-nginx
  template:
    metadata:
      labels:
        tier: hari-nginx
    spec:
      containers:
      - name: nginx
        image: nginx 
        ports:
        - containerPort: 80
        
---
#service port 
apiVersion: v1
kind: Service
metadata:
  name: expense
spec:
  type: NodePort
  selector:
    matchLabels:
      tier: hari-nginx
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
